"""Implementation of the ``ces scan`` command.

Deterministically walks the repository to produce a brownfield
inventory that later commands (`ces baseline`, `ces brownfield
register --from-scan`) can consume.

The scan output is written to ``.ces/brownfield/scan.json`` and
contains:
    * ``modules``        — detected module manifests (Python/Node/Go).
    * ``generated_files``— files whose first lines advertise
      generated/auto-generated status (protobuf, OpenAPI, codegen).
    * ``codeowners``     — parsed CODEOWNERS entries (pattern + owners).
    * ``scanned_at``     — UTC ISO-8601 timestamp.
    * ``root``           — repository root that was scanned.

No LLM calls. Pure filesystem walk + deterministic heuristics so
output is reproducible and reviewable.

Exports:
    scan: Typer command function for ``ces scan``.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import typer
from rich.panel import Panel

from ces.cli._output import console
from ces.cli.init_cmd import derive_project_name, initialize_local_project

# Directories skipped during the walk — vendor / build / VCS noise that
# would otherwise swamp the scan results and slow the command down.
_SKIP_DIR_NAMES: frozenset[str] = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        "node_modules",
        ".venv",
        "venv",
        ".tox",
        "dist",
        "build",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".ces",
    }
)

# How many leading bytes to sniff for a generated-code marker.
_GEN_HEADER_BYTES = 512

# Markers that indicate a file is code-generated.
_GEN_MARKERS: tuple[str, ...] = (
    "@generated",
    "DO NOT EDIT",
    "Code generated",
    "AUTOGENERATED",
    "AUTO-GENERATED",
    "This file is automatically generated",
)

# Module manifest filename → module kind label stored in the scan.
_MODULE_MANIFESTS: dict[str, str] = {
    "pyproject.toml": "python",
    "package.json": "node",
    "go.mod": "go",
    "Cargo.toml": "rust",
}


def _should_skip_dir(name: str) -> bool:
    return name in _SKIP_DIR_NAMES


def _detect_generated(path: Path) -> bool:
    """Return True if *path* begins with any known codegen marker."""
    try:
        with path.open("rb") as fh:
            head = fh.read(_GEN_HEADER_BYTES)
    except OSError:
        return False
    try:
        text = head.decode("utf-8", errors="ignore")
    except UnicodeDecodeError:
        return False
    return any(marker in text for marker in _GEN_MARKERS)


def _parse_codeowners(content: str) -> list[dict[str, object]]:
    """Parse a CODEOWNERS file into structured entries.

    Ignores blank lines and ``#`` comments. Each remaining line becomes
    ``{pattern, owners}``. Owners may be GitHub/GitLab handles (``@name``)
    or email addresses; we store them as-is.
    """
    entries: list[dict[str, object]] = []
    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        pattern, *owners = parts
        entries.append({"pattern": pattern, "owners": owners})
    return entries


def _find_codeowners(root: Path) -> list[dict[str, object]]:
    """Look for CODEOWNERS in the usual locations and parse the first match."""
    for candidate in ("CODEOWNERS", ".github/CODEOWNERS", "docs/CODEOWNERS"):
        path = root / candidate
        if path.is_file():
            return _parse_codeowners(path.read_text(encoding="utf-8"))
    return []


def _walk_repo(root: Path) -> tuple[list[dict[str, object]], list[str]]:
    """Walk ``root`` and return (module manifests, generated file paths)."""
    modules: list[dict[str, object]] = []
    generated: list[str] = []

    for current in root.rglob("*"):
        # Skip any path whose components include a blacklisted directory.
        rel_parts = current.relative_to(root).parts
        if any(_should_skip_dir(part) for part in rel_parts):
            continue
        if current.is_dir():
            continue

        rel_posix = current.relative_to(root).as_posix()
        filename = current.name

        if filename in _MODULE_MANIFESTS:
            modules.append(
                {
                    "path": rel_posix,
                    "type": _MODULE_MANIFESTS[filename],
                    "name": current.parent.name if current.parent != root else root.name,
                }
            )

        if _detect_generated(current):
            generated.append(rel_posix)

    modules.sort(key=lambda m: m["path"])  # type: ignore[arg-type, return-value]
    generated.sort()
    return modules, generated


def scan(
    root: Path | None = typer.Option(
        None,
        "--root",
        help="Root directory to scan (defaults to current working directory).",
    ),
) -> None:
    """Inventory the repository and write ``.ces/brownfield/scan.json``.

    Detects module manifests, generated files, and CODEOWNERS entries.
    No LLM calls — pure deterministic filesystem walk so downstream
    commands can rely on reproducible output.
    """
    # Resolve at call-time so the cwd actually matters (typer defaults
    # are captured at import and would otherwise pin this to the repo
    # root where the module was imported).
    effective_root = (root or Path.cwd()).resolve()
    if not effective_root.is_dir():
        raise typer.BadParameter(f"Root is not a directory: {effective_root}")
    root = effective_root
    ces_dir = root / ".ces"
    if not ces_dir.exists():
        initialize_local_project(root, name=derive_project_name(root.name))
    elif not (ces_dir / "config.yaml").is_file():
        raise typer.BadParameter(
            f"{ces_dir} exists but is not a complete CES project. "
            "Move it aside or restore .ces/config.yaml before scanning."
        )

    modules, generated = _walk_repo(root)
    codeowners = _find_codeowners(root)

    report = {
        "root": str(root),
        "scanned_at": datetime.now(timezone.utc).isoformat(),
        "modules": modules,
        "generated_files": generated,
        "codeowners": codeowners,
    }

    out_dir = ces_dir / "brownfield"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "scan.json"
    out_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    console.print(
        Panel(
            f"Scanned [bold]{root}[/bold]\n"
            f"  modules:         {len(modules)}\n"
            f"  generated files: {len(generated)}\n"
            f"  codeowners:      {len(codeowners)}\n"
            f"  report:          {out_path}",
            title="[green]Brownfield scan complete[/green]",
            border_style="green",
        )
    )
